package io.pine.examples.cargo.domain.model.cargo;

import io.pine.examples.cargo.domain.shared.ValueObject;
import org.springframework.util.Assert;

/**
 * Uniquely identifies a particular cargo. Automatically generated by the application.
 *
 * @author Frank
 * @sinace 2018/8/9 0009.
 */
public final class TrackingId implements ValueObject<TrackingId> {
    private String id;

    public TrackingId(final String id) {
        Assert.hasText(id, "id should not empty");
        this.id = id;
    }
    @Override
    public boolean equals(Object o) {
        if (this == o) { return true; }
        if (o == null || getClass() != o.getClass()) { return false; }

        TrackingId other = (TrackingId) o;

        return sameValueAs(other);
    }

    @Override
    public int hashCode() {
        return id.hashCode();
    }

    @Override
    public boolean sameValueAs(TrackingId other) {
        return other != null && this.id.equals(other.id);
    }

    @Override
    public String toString() {
        return id;
    }
}
