package io.pine.examples.cargo.domain.model.cargo;

import io.pine.examples.cargo.domain.shared.ValueObject;
import org.springframework.util.Assert;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import java.util.UUID;

/**
 * Uniquely identifies a particular cargo. Automatically generated by the application.
 *
 * @author Frank
 * @sinace 2018/8/9 0009.
 */
@Embeddable
public final class TrackingId implements ValueObject<TrackingId> {
    @Column(name = "tracking_id", unique = true, updatable = false)
    private String id;

    TrackingId() {}

    public TrackingId(final String id) {
        Assert.hasText(id, "id should not empty");
        this.id = id;
    }
    @Override
    public boolean equals(Object o) {
        if (this == o) { return true; }
        if (o == null || getClass() != o.getClass()) { return false; }

        TrackingId other = (TrackingId) o;

        return sameValueAs(other);
    }

    public static TrackingId nextTrackingId() {
        // TODO use an actual DB sequence here, UUID is for in-mem
        final String random = UUID.randomUUID().toString().toUpperCase();
        return new TrackingId(
                random.substring(0, random.indexOf("-"))
        );
    }

    @Override
    public int hashCode() {
        return id.hashCode();
    }

    @Override
    public boolean sameValueAs(TrackingId other) {
        return other != null && this.id.equals(other.id);
    }

    @Override
    public String toString() {
        return id;
    }
}
